EngFlow/bazel_invocation_analyzer

cli/java/com/engflow/bazel/invocation/analyzer/Main.java, cli/java/com/engflow/bazel/invocation/analyzer/consoleoutput/ConsoleOutput.java, cli/javatests/com/engflow/bazel/invocation/analyzer/consoleoutput/ConsoleOutputTest.java
Instead of outputting the suggestions per `SuggestionOutput` (and this per `SuggestionProvider`) collect all failures, top-level caveats, and suggestions. First output all top-level caveats, then all failures, and finally all suggestions, ordered by descending potential improvement. Also space out the suggestions a bit more for more visual separation.
Fixes #7
=> CLI: Restructure output and sort suggestions by potential improvement

analyzer/javatests/com/engflow/bazel/invocation/analyzer/core/TestDatum.java, cli/java/com/engflow/bazel/invocation/analyzer/consoleoutput/ConsoleOutput.java, cli/javatests/com/engflow/bazel/invocation/analyzer/consoleoutput/ConsoleOutputTest.java
When running the CLI and requesting the data extracted from the Bazel profile, we omit `Datum`s whose summary is empty.
With this change, in verbose mode, the reason why the `Datum` is empty is output (if set), rather than skipping the `Datum`.
=> CLI: In verbose mode, include in data dump the reason for empty Datums

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfile.java, analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/ProfileThread.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/WriteBazelProfile.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfileTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/CriticalPathDurationDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/EstimatedCoresDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/GarbageCollectionStatsDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/MergedEventsPresentDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/remoteexecution/CriticalPathQueuingDurationDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/remoteexecution/QueuingObservedDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/remoteexecution/RemoteCachingUsedDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/remoteexecution/RemoteExecutionUsedDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/remoteexecution/TotalQueuingDurationDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/GarbageCollectionSuggestionProviderTest.java
Fixes #54
When passing in valid json files that are missing key components of a Bazel profile, an NPE is thrown.
This change checks for the key components before trying to access them and throws an IllegalArgumentException if the components do not exist.
=> Core: Avoid NPEs on invalid Bazel profiles

analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/CriticalPathDurationDataProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/IncompleteProfileSuggestionProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProviderUtil.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/CriticalPathDurationDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/BUILD, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/IncompleteProfileSuggestionProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProvidersTestSuite.java
Many of the `SuggestionProvider`s only supply suggestions if the Bazel profile was generated for a build-like command. This change adds a suggestion to analyze such a profile if the passed in profile looks like it was generated for a non-build-like command (e.g. query).
Example output:
```text
Suggestion: "Analyze a different Bazel profile"
Consider analyzing a different Bazel profile. Many evaluations depend on the profile reporting some action execution. This will usually be the case when invoking a build-like Bazel command, such as `bazel build` or `bazel test`.
Rationale
The Bazel profile does not include a critical path.
The Bazel profile does not include the data required to estimate how many cores were available on the machine that the invocation was run on.
The Bazel profile does …
```
=> Analyzer: Add a SuggestionProvider for profiles with little data

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfileConstants.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/remoteexecution/RemoteExecutionUsedDataProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/remoteexecution/RemoteExecutionUsedDataProviderTest.java
Currently `RemoteExecutionUsedDataProvider` is too lenient with how it checks whether remote execution was likely used. This leads to false positives, in particular when using remote caching or a disk cache.
Instead of checking for events with the category `Remote execution process wall time`, which also occurs for non-RE builds, now check for events with the category `remote action execution` and name `execute remotely`. This seems to be a stronger signal for remote execution.
Progress on #60
=> RemoteExecutionUsed: Avoid false positives with stricter checks

analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/BottleneckSuggestionProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/CriticalPathNotDominantSuggestionProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/GarbageCollectionSuggestionProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/NegligiblePhaseSuggestionProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/QueuingSuggestionProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/time/DurationUtil.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/BottleneckSuggestionProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/time/DurationUtilTest.java
We are calculating the percentage of durations in multiple places. This change introduces a convenience method to ensure these calculations are all consistent, and replaces the individual implementations with a call to the new method.
=> DurationUtil: add convenience method `getPercentageOf`

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfile.java
To ease debugging, extend `BazelProfile#getSummary` to include some data about the threads found.
Example output:
```
BazelProfile: The profile written by Bazel.
Threads:
"Critical Path"                     	CompleteEvents: 1
"Garbage Collector"                 	CompleteEvents: 1
"Main Thread"                       	CompleteEvents: 2630	Counts: 5	Instants: 2
"skyframe-evaluator 0"              	CompleteEvents: 47
"skyframe-evaluator 1"              	CompleteEvents: 51
"skyframe-evaluator 10"             	CompleteEvents: 56
"skyframe-evaluator 11"             	CompleteEvents: 42
"skyframe-evaluator 12"             	CompleteEvents: 37
"skyframe-evaluator 13"             	CompleteEvents: 42
"skyframe-evaluator 14"             	CompleteEvents: 42
"skyframe-evaluator 15" …
```
=> BazelProfile: In summary, include data about threads

analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/ActionStats.java
Currently, when there's exactly one bottleneck, `getSummary` returns `1 bottlenecks found`. This change ensures we return `1 bottleneck found` instead.
=> ActionStats: Better singular/plural handling in `getSummary`

README.md
This change
* adds a section on how to contact us
* highlights the guide on contributing
* updates the links in the "References" section
=> Docs: Extend README to include contact and contributing info

README.md
Update the link on how to generate a Bazel profile to link to the correct heading.
Follow-up to https://github.com/EngFlow/bazel_invocation_analyzer/pull/70#discussion_r1008332933
=> Docs: Link to relevant FAQ question

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfile.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfileTest.java
When trying to parse the `BazelProfile`, we make assumptions about the structure of the passed in JSON. Wrap the parsing in a try-catch block and wrap any `IllegalStateException`s in `IllegalArgumentException`s. These may be thrown on `getAsJsonObject`, if the JSON element is not an object.
=> BazelProfile: Better handling of invalid profiles

analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/BottleneckSuggestionProvider.java
In the verbose settings, `maxActionCountRatio` was incorrectly set to `0`, instead of the desired `1`. This change fixes that. It also adds some zero duration checks to avoid exceptions being thrown when trying to divide by zero.
=> BottleneckSuggestionProvider: Fix verbose settings

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/feedback.md, CONTRIBUTING.md, README.md, cli/java/com/engflow/bazel/invocation/analyzer/consoleoutput/ConsoleOutput.java
This email address is easier to remember than the longer one.
=> Docs: Update contact email address to analyzer@engflow.com

README.md
Include in `README.md` a reference to the public web UI available at https://analyzer.engflow.com
=> Docs: Reference public web UI

analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/RemoteCacheMetrics.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/RemoteCacheMetricsDataProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/LocalActionsDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/RemoteCacheMetricsDataProviderTest.java
`RemoteCacheMetrics` throws an NPE when it is empty. This change fixes that bug and adds a test for it. It also restructures `RemoteCacheMetricsDataProviderTest` to use `DataProviderUnitTestBase`, and adds a test to `LocalActionsDataProviderTest` for the empty case.
Follow-up to #88.
Bug observed in https://github.com/EngFlow/engflow/pull/13483
=> [DataProvider] Fix NPE in RemoteCacheMetrics

WORKSPACE, infra/BUILD, infra/lint.sh, third_party/google-java-format/BUILD
Right now, we are linting our Java files in a non-hermetic way. This change creates a `java_binary` that is run instead of using `java -jar` in the lint script.
Also see https://github.com/EngFlow/website/pull/284
=> [infra] Hermetic java linting

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfileConstants.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/BazelVersion.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/BazelVersionDataProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/DataProviderUtil.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/BazelVersionDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/DataProvidersTestSuite.java
With Bazel release 6.1.0 the Bazel profile includes which version of Bazel generated the profile. This PR adds a DataProvider that extracts that information, if it is included.
Fixes #109
=> [DataProvider] Extract Bazel version from profile, if present

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfile.java, analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfileConstants.java, analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/ProfileThread.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfileTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/GarbageCollectionStatsDataProviderTest.java
The thread in which GC events are listed has been renamed multiple times, so the code for extracting the right thread by name is error-prone.
Instead of testing the name, search for the GC thread by its included events. This assumes that there is only one thread that contains GC events.
Contributes to #110
=> [BazelProfile] More robust GC thread identification

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfilePhase.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/BUILD, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/DataProviderUtil.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/EstimatedCoresDataProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/SkymeldUsed.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/SkymeldUsedDataProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/NegligiblePhaseSuggestionProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/ProfileTestBase.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/BazelPhaseDescriptionsTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/BazelPhasesDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/BazelProfilePhaseTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/DataProvidersTestSuite.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/EstimatedCoresDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/SkymeldUsedDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/integrationtests/NegligiblePhaseSuggestionProviderIntegrationTest.java
As a first step to supporting Bazel profiles where Skymeld was used, add a `Datum` that indices whether the profile looks like it was generated while using Skymeld.
Contributes to #91
Contributes to #97
=> [DataProvider] Add `SkymeldUsed` Datum and provide it

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BUILD, analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfile.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/BUILD, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/BazelVersion.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/BazelVersionDataProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/bazelprofile/BUILD, analyzer/javatests/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfileTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/BazelVersionDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/BazelVersionTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/DataProvidersTestSuite.java
The functionality provided by `BazelProfile` may need to take the Bazel version into consideration. Therefore, this PR makes the version available within and through the `BazelProfile`, while `BazelVersionDataProvider` stays in place to provide easier access, as well as memoization.
Contributes to #109.
=> [BazelProfile] Make `BazelVersion` available in `BazelProfile

analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/GarbageCollectionStats.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/GarbageCollectionStatsDataProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/GarbageCollectionSuggestionProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/GarbageCollectionStatsDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/GarbageCollectionSuggestionProviderTest.java
Currently, a Bazel profile with no GC threads is identified as invalid. However, in some cases valid Bazel profiles may not include any garbace collection events.
With this PR we no longer throw an error if no GC is found, but rather emit a warning that no GC analysis could be performed.
Contributes ton #110.
=> [GarbageCollection] Do not fail on missing GC thread.

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BUILD, analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfileConstants.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/BUILD, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/LocalActions.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/LocalActionsDataProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/RemoteCacheMetricsDataProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/remoteexecution/BUILD, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/LocalActionsWithRemoteExecutionSuggestionProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProviderUtil.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/EventThreadBuilder.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/LocalActionsDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/RemoteCacheMetricsDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/remoteexecution/BUILD, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/BUILD, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/LocalActionsWithRemoteExecutionSuggestionProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProvidersTestSuite.java
Add a `SuggestionProvider` which, if remote execution is used, highlights which actions were run locally and suggests migrating them to remote execution, too. In default mode, the four longest local actions are listed.
Fixes #95.
=> [SuggestionProvider] Highlight locally executed actions when remote execution is used

analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/EstimatedCoresAvailable.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/EstimatedCoresDataProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/EstimatedCoresUsed.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/SkymeldUsed.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/SkymeldUsedDataProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/CriticalPathNotDominantSuggestionProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/EstimatedCoresDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/SkymeldUsedDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/integrationtests/JobsSuggestionProviderIntegrationTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/CriticalPathNotDominantSuggestionProviderTest.java
This change adds support for analysing profiles generated when using Skymeld. For this, the interlaced analysis and execution phase is split into two parts:
1. Analysis only, no execution interlaced.
2. Execution has started. analysis and execution may be interlaced.
This is done by checking for the first observed `action processing` event. The distinction is relevant, because it helps us determine how many cores are available on the machine that ran the Bazel client, as well has how many cores are used during execution. The later may be higher than the prior, e.g. when remote execution is used.
* Update `SkymeldUsed` to include the combined analysis and execution phase, as well as optionally the phase at which execution likely starts.
* Update `EstimatedCoresDataProvider` to estimate …
=> [Skymeld] Adjust `DataProvider`s and `SuggestProvider`s for Skymeld

analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProviderUtil.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/UseSkymeldSuggestionProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProvidersTestSuite.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/UseSkymeldSuggestionProviderTest.java
If the profile indicates Skymeld was not used, suggest enabling it. A caveat is included if the Bazel profile doesn't report a Bazel version that supports Skymeld
Fixes #91
=> [SuggestionProvider] Suggest using Skymeld

CODEOWNERS
* Remove broken `@Engflow/admin` entry
* Remove Antonio and Corbin
* Add Laszlo
=> [CODEOWNERS] Update who is automatically added as a reviewer

analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/LocalActionsWithRemoteExecutionSuggestionProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/LocalActionsWithRemoteExecutionSuggestionProviderTest.java
This change includes a fix, where empty suggestions were added if
* the invocation used remote execution
* no actions were executed locally.
Follow-up to #119
Contributes to #95
=> [LocalActionsWithRemoteExecutionSuggestionProvider] Fix bug where empty suggestions were included

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfileConstants.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/BUILD, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/DataProviderUtil.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/FlagValueDataProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/FlagValueExperimentalProfileIncludeTargetLabel.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/BottleneckSuggestionProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/EventThreadBuilder.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/WriteBazelProfile.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/DataProvidersTestSuite.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/FlagValueDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/BottleneckSuggestionProviderTest.java
When using the flag `--experimental_profile_include_target_label` when a Bazel profile is generated, action processing events include which target the action is being processed for.
If present, add this information to the "Break down bottlenecks" suggestions. If not present, add a caveat that highlights the flag could be set to improve the bottleneck suggestions.
Fixes #92.
=> [BottleneckSuggestionProvider] Add target for action, if available.

analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/InvestigateRemoteCacheMissesSuggestionProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProviderUtil.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/InvestigateRemoteCacheMissesSuggestionProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProvidersTestSuite.java
If remote caching is used and there are remote cache misses, suggest investigating the misses with a link to Bazel documentation.
Contributes to #90
=> [SuggestionProvider] Suggest investigating remote cache misses

analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/remoteexecution/RemoteCachingUsedDataProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProviderUtil.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/UseRemoteCachingSuggestionProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/remoteexecution/RemoteCachingUsedDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProvidersTestSuite.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/UseRemoteCachingSuggestionProviderTest.java
If the profile looks like remote caching was not used, suggest setting it up. The suggestion mentions both `--remote_cache` and `--disk_cache` as options that you can combine, and links to Bazel documentation.
Fixes #127
=> [SuggestionProvider] Suggest using a remote cache, if not done yet

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelEventsUtil.java, analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfileConstants.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/LocalActionsDataProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelEventsUtilTest.java
Extend the analysis to find further events that indicate outputs were downloaded from a remote resource. This improves the detection of remotely executed events.
=> [DataProvider] Detect additional "remote download output" events

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BUILD, analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelEventsUtil.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/FlagValueExperimentalProfileIncludeTargetLabel.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/BUILD, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/BottleneckSuggestionProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/InvestigateRemoteCacheMissesSuggestionProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/LocalActionsWithRemoteExecutionSuggestionProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelEventsUtilTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/LocalActionsWithRemoteExecutionSuggestionProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProvidersTestSuite.java
This refactors some code, so that the way action processing events are printed out consistently, rather than having duplicate code.
It also refactors the code, so it's easy to add caveats relating to a profile not having the target names attached to actions.
Contributes to #133
=> [Refactor] Extract common methods: summary for complete event, target name missing info

analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/NoCacheActionsSuggestionProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProviderUtil.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/NoCacheActionsSuggestionProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/suggestionproviders/SuggestionProvidersTestSuite.java
If remote caching is enabled and the profile includes actions that do not check the remote cache, add a suggestion to investigate whether they could be cached.
Motivated by https://github.com/EngFlow/bazel_invocation_analyzer/pull/128#discussion_r1406225408
Fixes #133
=> [SuggestionProvider] Add suggestion to investigate no-cache actions

analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/CachingAndExecutionMetrics.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/CachingAndExecutionMetricsDataProvider.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/DataProviderUtil.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/RemoteCacheMetrics.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/CachingAndExecutionMetricsDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/DataProvidersTestSuite.java
This data provider scans all actions and splits them into:
* remote cache hit
* remote cache miss
* remote cache not checked
as well as (for non-cache-hits):
* executed locally
* executed remotely
* execution location not reported
"Internal" Bazel actions are included in "remote cache not checked" and "execution location not reported".
While I invested ample time in trying to single internal actions out reliably, I did not succeed. I'm not sure it's possible with the information currently written to profiles. A TODO to look into separating out "internal" actions is in the code.
Contributes to #90
=> [DataProvider] Add provider for metrics on caching status and execution location

analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/LocalActions.java, analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/InvestigateRemoteCacheMissesSuggestionProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/DataProvidersTestSuite.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/LocalActionsDataProviderTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/LocalActionsTest.java
When highlighting cache misses sorted by their duration, exclude the time spent for checking the remote cache. This is more reflective of which cache misses you want to fix.
Contributes to #90
=> [SuggestionProvider] Sort highlighted cache misses by execution time

analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/RemoteCacheMetrics.java, analyzer/java/com/engflow/bazel/invocation/analyzer/dataproviders/RemoteCacheMetricsDataProvider.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/dataproviders/RemoteCacheMetricsDataProviderTest.java
Both `RemoteCacheMetrics` and `CachingAndExecutionMetrics` estimate the number of cache checks and cache misses/hits. This change removes the analysis from `RemoteCacheMetrics`, as `CachingAndExecutionMetrics` seems to extract more precise data.
Fixes #156
=> [DataProvider] Simplify `RemoteCacheMetrics`

analyzer/java/com/engflow/bazel/invocation/analyzer/traceeventformat/CompleteEvent.java, analyzer/java/com/engflow/bazel/invocation/analyzer/traceeventformat/CounterEvent.java, analyzer/java/com/engflow/bazel/invocation/analyzer/traceeventformat/InstantEvent.java
When reading the profile, many strings are encountered multiple times. Use `String.interner()` to reduce the memory requirements of running the analyzer.
Benchmark with a Bazel profile of unzipped size 357MB Using YourKit as a profiler and checking the shallow size just before generating the suggestions:
Before: 692 MB
After:  349 MB
Progress on #163
=> [Performance] Use interner to de-duplicate strings

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfile.java
Instead of reading the Bazel profile all at once, use a stream to reduce memory consumption.
Benchmark with a Bazel profile of unzipped size 357MB
Using YourKit as a profiler and checking the shallow size at the end of the `BazelProfile` constructor:
Before: 3.6 GB
After: 349 MB
Contributes to #163
=> [Performance] Read Bazel profile as a stream

.bazelrc, MODULE.bazel.lock
=> Add .bazelrc entries for running `bazel coverage`

analyzer/java/com/engflow/bazel/invocation/analyzer/suggestionproviders/JobsSuggestionProvider.java
The present change aims at removing the redundant `of` in the suggested improvement to leave the `--jobs` flags unset:
- CLI:
- UI:
```patch
-Unset the value of of the Bazel flag --jobs
+Unset the value of the Bazel flag --jobs
```
=> Fix minor typo in the tip to leave `--jobs` unset

analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/ProfileThread.java, analyzer/java/com/engflow/bazel/invocation/analyzer/traceeventformat/CompleteEvent.java, analyzer/java/com/engflow/bazel/invocation/analyzer/traceeventformat/CounterEvent.java, analyzer/java/com/engflow/bazel/invocation/analyzer/traceeventformat/InstantEvent.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/traceeventformat/BUILD, analyzer/javatests/com/engflow/bazel/invocation/analyzer/traceeventformat/CompleteEventTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/traceeventformat/CounterEventTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/traceeventformat/InstantEventTest.java, analyzer/javatests/com/engflow/bazel/invocation/analyzer/traceeventformat/TraceEventFormatTestSuite.java
When creating trace event format events, the code used to throw NullPointerExceptions when trying to construct an event from a JsonObject that was missing required members.
This change adds static `fromJson` methods, which check the members exist, or otherwise throw an IllegalArgumentException. This better communicates the kind of error that occurred - the provided Json did not have the expected form.
This change also adds some basic documentation and tests for the Event classes.
=> [Core] Avoid NPEs on creating events
